[global]
[hasura]
version = 'v2.36.1'
adminSecret = '{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[hasura.jwtSecrets]
type = 'HS256'
key = '{{ secrets.HASURA_GRAPHQL_JWT_SECRET }}'

[hasura.settings]
corsDomain = ['*']
enableConsole = true
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']

[functions]
[functions.node]
version = 18

[auth]
version = '0.25.0'
[auth.redirections]
clientUrl = 'http://localhost:3000'
allowedUrls = ['http://localhost:3000']
[auth.method.emailPassword]
emailVerificationRequired = false

[postgres]
version = '14.6-20230925-1'

[provider]
[storage]
version = '0.4.0'
